/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puppersdaa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ignac
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        initComponents();
        setupButtonListeners();
        setupWindowListener();
        centerWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        updateTxt = new javax.swing.JTextArea();
        destinationDrop = new javax.swing.JComboBox<>();
        sourceDrop = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Mode");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateTxt.setBackground(new java.awt.Color(221, 87, 70));
        updateTxt.setColumns(20);
        updateTxt.setForeground(new java.awt.Color(254, 250, 246));
        updateTxt.setRows(5);
        updateTxt.setBorder(null);
        updateTxt.setPreferredSize(new java.awt.Dimension(158, 90));
        jScrollPane1.setViewportView(updateTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 403, 530, 120));

        destinationDrop.setBackground(new java.awt.Color(221, 87, 70));
        destinationDrop.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        destinationDrop.setForeground(new java.awt.Color(254, 250, 246));
        destinationDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main Gate", "Information Desk", "Visitor's Lounge", "Souvenir Shop", "Oval", "Obelisk", "Pool", "College of Human Kinetics", "Lagoon", "Amphitheater", "Main Dome", "Chapel", "East Wing", "West Wing", "South Wing", "Tahanan ng Alumni", "Tennis Court", "Gymnasium", "School Supplies and Printing Bldg.", "Printing Press", "Ninoy Aquino Library and Learning Resource Center", "Property and Supply Office Bldg", "Charlie del Rosario Bldg.", "Engineering and Research Center", "Sampaguita Canteen", "Pumping Station", "Food Tech Research Center", "FAMO", "Linear Park", "Laboratory High" }));
        destinationDrop.setBorder(null);
        destinationDrop.setLightWeightPopupEnabled(false);
        getContentPane().add(destinationDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 210, 30));

        sourceDrop.setBackground(new java.awt.Color(221, 87, 70));
        sourceDrop.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sourceDrop.setForeground(new java.awt.Color(254, 250, 246));
        sourceDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main Gate", "Information Desk", "Visitor's Lounge", "Souvenir Shop", "Oval", "Obelisk", "Pool", "College of Human Kinetics", "Lagoon", "Amphitheater", "Main Dome", "Chapel", "East Wing", "West Wing", "South Wing", "Tahanan ng Alumni", "Tennis Court", "Gymnasium", "School Supplies and Printing Bldg.", "Printing Press", "Ninoy Aquino Library and Learning Resource Center", "Property and Supply Office Bldg", "Charlie del Rosario Bldg.", "Engineering and Research Center", "Sampaguita Canteen", "Pumping Station", "Food Tech Research Center", "FAMO", "Linear Park", "Laboratory High" }));
        sourceDrop.setBorder(null);
        getContentPane().add(sourceDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 210, 30));

        jButton2.setBackground(new java.awt.Color(221, 87, 70));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 250, 246));
        jButton2.setText("Update");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 546, 90, 30));

        jButton1.setBackground(new java.awt.Color(221, 87, 70));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 250, 246));
        jButton1.setText("Return");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 546, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puppersdaa/FrameAdmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateLocationInformation();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void updateLocationInformation() {
        String source = (String) sourceDrop.getSelectedItem();
        String destination = (String) destinationDrop.getSelectedItem();
        String information = updateTxt.getText();
        JOptionPane.showMessageDialog(this,
            String.format("Updated information:\nSource: %s\nDestination: %s\nInformation: %s",
                source, destination, information),
            "Update Confirmation",
            JOptionPane.INFORMATION_MESSAGE);
    }        
    
    private void setupButtonListeners() {
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                returnToLandingPage();
            }
        });
    }
    
    private void returnToLandingPage() {
        LandingPage landingPage = new LandingPage();
        landingPage.setVisible(true);
        landingPage.setLocationRelativeTo(null);
        this.dispose();
    }
    
    private void setupWindowListener() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                returnToLandingPage();
            }
        });
    }
    
    private void centerWindow() {
        setLocationRelativeTo(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminGUI adminGUI = new AdminGUI();
                adminGUI.setVisible(true);
                adminGUI.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destinationDrop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sourceDrop;
    private javax.swing.JTextArea updateTxt;
    // End of variables declaration//GEN-END:variables
}
